[package]
name = 'Airdrop'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
MosquitoCoin = { local = "../MosquitoCoin" }
[addresses]
MasterChefDeployer = "0x4db735a9d57f0ed393e44638540efc8e2ef2dccca3bd30c29bd09353b6285832"
AirdropDeployer = "0x28e49b130141ff36c361794be1451f0493264b49bae3e8eaac2bda034d0c5daf"
